#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

cd $OPENSHIFT_REPO_DIR
nohup python main.py stop pre_build > $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &