#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

cd $OPENSHIFT_REPO_DIR
chmod 600 ./ssh/id_rsa
chmod 600 ./mongo/repl_key
nohup python main.py try_start start > $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &